Correct data for qa dashboards from dev versions including load balancers
3box/ceramic-stats pull request #42
Opened 2022-08-23 20:43 UTC by gvelez17

Changes to the dev dashboards to adapt to qa, mainly boilerplate except the load balancers pulled from AWS

2022-08-23 21:57 UTC, v-stickykeys requested changes
Just 2 lines that I think need to be updated

2022-08-23 21:57 UTC, v-stickykeys commented on grafana/provisioning/dashboards/qa/anchorservice.json
> +                        "LoadBalancer": "app/ceramic-qa-cas-ipfs-nd-alb-ex/190eb438ebba5068",
Does this lb id need to change?

2022-08-23 21:57 UTC, v-stickykeys commented on grafana/provisioning/dashboards/qa/anchorservice.json
> +                        "LoadBalancer": "app/ceramic-qa-cas-ipfs-nd-alb-in/5f1227f17a902fe2",
Does this lb id need to change?

2022-08-23 21:59 UTC, v-stickykeys commented
Also need the pubsub metrics filters deployed to AWS for those dashboards to work properly. See https://github.com/3box/ceramic-utils-lambda/blob/dev/src/scripts/generate-metric-filters.sh

2022-08-23 23:06 UTC, gvelez17 commented on grafana/provisioning/dashboards/qa/anchorservice.json
> +                        "LoadBalancer": "app/ceramic-qa-cas-ipfs-nd-alb-in/5f1227f17a902fe2",
aaah - missed two!  yes, fixed!

2022-08-23 23:07 UTC, gvelez17 commented on grafana/provisioning/dashboards/qa/anchorservice.json
> +                        "LoadBalancer": "app/ceramic-qa-cas-ipfs-nd-alb-ex/190eb438ebba5068",
yes!

2022-08-23 23:10 UTC, v-stickykeys approved these changes

2022-09-05 23:43 UTC, gvelez17 commented
@smrz2001 I am going to merge this now but just fyi this is the thing we need to replace entirely soon https://github.com/3box/ceramic-stats/pull/42/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R32

2022-09-05 23:43 UTC, merged